### ISSUE TITLE
Running ./ready? requires at least Python 3.9

### ISSUE THREAD

**Issue by zakhard90** [iburzynski/jambhala#5]
The documentation should probably mention the minimum Python version requirement as I encountered an error with version 3.8.10 which occurred while running the `./ready? ` script.

`Traceback (most recent call last):
  File "setup/readiness_test.py", line 20, in <module>
    "flags": list[str],
TypeError: 'type' object is not subscriptable`

After upgrading to 3.9 the script worked as expected.

**Comment by iburzynski** [comment]
Thanks for this Zakhar

**Comment by iburzynski** [comment]
Thanks Zakhar. The 'ready?' script is supposed to determine if the user has the minimum required version of Python to run the readiness check, and if not it runs the check in a transient Nix shell with the necessary Python version installed. The problem was that the minimum version threshold was set too low (>= 3.6), as I mistakenly thought this version would be sufficient. I've bumped the version to 3.9 now, so the script should work for everyone regardless of whether they have Python 3.9+ or not.
